server:
  port: 2021
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://118.195.145.14:3306/waltersun?useUnicode=true&characterEncoding=utf8&allowMultiQueries=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: walter
    password: qweQWE123!@#

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志配置
logging:
  file:
    name: waltersun.log
    path: /home/waltersun/
  level:
    root: error
    com.waltersun.lastesttech: info
    com.waltersun.lastesttech.service: debug

#线程池配置
async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 5
      queue_capacity: 99999
      name:
        prefix: async-service-