server:
  port: 2021
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /api

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://118.195.145.14:3306/mysql?useUnicode=true&characterEncoding=utf8&allowMultiQueries=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

logging:
  file:
    name: waltersun.log
    path: /home/waltersun/
