server:
  port: 2021
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://118.195.145.14:3306/waltersun?useUnicode=true&characterEncoding=utf8&allowMultiQueries=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: walter
    password: qweQWE123!@#

logging:
  file:
    name: waltersun.log
    path: /home/waltersun/

downloadPath: E:\tempnew\