# java -jar lastesttech-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
server:
  port: 2021
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://118.195.145.14:3306/waltersun?useUnicode=true&characterEncoding=utf8&allowMultiQueries=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: walter
    password: qweQWE123!@#
  redis:
    host: 118.195.145.14
    port: 6379
    password: redis
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
  kafka:
    bootstrap-servers: 118.195.145.14:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      auto-commit-interval: 1S
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 5
      ack-mode: manual_immediate
      missing-topics-fatal: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志配置
logging:
  file:
    name: waltersun.log
    path: /home/waltersun/
  level:
    root: error
    com.waltersun.lastesttech: info

#线程池配置
async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 5
      queue_capacity: 99999
      name:
        prefix: async-service-

# jetcache缓存相关配置
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 118.195.145.14
      port: 6379
      password: redis